INSERT INTO `dims_constant` (`id`, `moduletype`, `id_lang`, `value`, `phpvalue`) 
VALUES  (NULL, 'system', '1', "Ecrire un nouveau message", '_DIMS_LABEL_TICKET_WRITE_NEW_TICKET'),
        (NULL, 'system', '1', "Ecrire un nouveau message au client", '_DIMS_LABEL_TICKET_WRITE_NEW_TICKET_TO_CUSTOMER'),
        (NULL, 'system', '1', "Ecrire un nouveau message au client", '_DIMS_LABEL_TICKET_WRITE_NEW_TICKET_TO_CUSTOMER'),
        (NULL, 'system', '1', "R&eacute;diger un message", '_DIMS_LABEL_TICKET_WRITING_TICKET'),
        (NULL, 'system', '1', "Accus&eacute; de r&eacute;ception", '_DIMS_LABEL_TICKET_ACCUSE_RECEPTION'),
        (NULL, 'system', '1', "Suivre le message", '_DIMS_LABEL_TICKET_FOLLOW_TICKET'),
        (NULL, 'system', '1', "Destinataires", '_DIMS_LABEL_TICKET_DESTINATAIRES'),
        (NULL, 'system', '2', "Inbox", '_DIMS_LABEL_TICKET_INBOX'),
        (NULL, 'system', '2', "Outbox", '_DIMS_LABEL_TICKET_OUTBOX'),
        (NULL, 'system', '2', "Drafts", '_DIMS_LABEL_TICKET_DRAFTS'),
        (NULL, 'system', '2', "Archives", '_DIMS_LABEL_TICKET_ARCHIVES'),
        (NULL, 'system', '2', "Junk", '_DIMS_LABEL_TICKET_JUNK'),
        (NULL, 'system', '2', "Follow", '_DIMS_LABEL_TICKET_FOLLOW'),
        (NULL, 'system', '1', "Boîte de réception", '_DIMS_LABEL_TICKET_INBOX'),
        (NULL, 'system', '1', "Boîte d'envoi", '_DIMS_LABEL_TICKET_OUTBOX'),
        (NULL, 'system', '1', "Brouillons", '_DIMS_LABEL_TICKET_DRAFTS'),
        (NULL, 'system', '1', "Archives", '_DIMS_LABEL_TICKET_ARCHIVES'),
        (NULL, 'system', '1', "Corbeille", '_DIMS_LABEL_TICKET_JUNK'),
        (NULL, 'system', '1', "A suivre", '_DIMS_LABEL_TICKET_FOLLOW'),
        (NULL, 'system', '1', "Auteur", '_DIMS_LABEL_TICKET_AUTHOR'),
        (NULL, 'system', '2', "Author", '_DIMS_LABEL_TICKET_AUTHOR'),
        (NULL, 'system', '1', "Objet", '_DIMS_LABEL_TICKET_SUBJECT'),
        (NULL, 'system', '2', "Subject", '_DIMS_LABEL_TICKET_SUBJECT'),
        (NULL, 'system', '1', "PJ", '_DIMS_LABEL_TICKET_ATTACHMENTS_SHORT'),
        (NULL, 'system', '2', "ATT", '_DIMS_LABEL_TICKET_ATTACHMENTS_SHORT'),
        (NULL, 'system', '1', "Pi&egrave;ce jointe", '_DIMS_LABEL_TICKET_ATTACHMENTS'),
        (NULL, 'system', '2', "Attachement", '_DIMS_LABEL_TICKET_ATTACHMENTS'),
        (NULL, 'system', '1', "Rien", '_DIMS_LABEL_TICKET_NO_ATTACHEMENTS'),
        (NULL, 'system', '2', "Nothing", '_DIMS_LABEL_TICKET_NO_ATTACHEMENTS'),
        (NULL, 'system', '1', "Voir", '_DIMS_LABEL_TICKET_SEE'),
        (NULL, 'system', '2', "See", '_DIMS_LABEL_TICKET_SEE'),
        (NULL, 'system', '1', "Aucun message selectionné", '_DIMS_LABEL_TICKET_NO_TICKET_SELECTED'),
        (NULL, 'system', '1', "Consulter un message", '_DIMS_LABEL_TICKET_CONSULT_TICKET'),
        (NULL, 'system', '1', "Message suivi", '_DIMS_LABEL_TICKET_FOLLOWED'),
        (NULL, 'system', '1', "Archiver", '_DIMS_LABEL_TICKET_TO_ARCHIVE'),
        (NULL, 'system', '1', "Transférer", '_DIMS_LABEL_TICKET_TO_TRANSFER'),
        (NULL, 'system', '1', "le groupe", '_DIMS_LABEL_TICKET_THE_GROUP'),
        (NULL, 'system', '1', "pour", '_DIMS_LABEL_TICKET_DEST_FOR'),
        (NULL, 'system', '2', "for", '_DIMS_LABEL_TICKET_DEST_FOR'),
        (NULL, 'system', '1', "cc", '_DIMS_LABEL_TICKET_DEST_CC_SHORT'),
        (NULL, 'system', '2', "cc", '_DIMS_LABEL_TICKET_DEST_CC_SHORT'),
        (NULL, 'system', '1', "cci", '_DIMS_LABEL_TICKET_DEST_CCI_SHORT'),
        (NULL, 'system', '2', "bcc", '_DIMS_LABEL_TICKET_DEST_CCI_SHORT'),
        (NULL, 'system', '1', "Copie Carbone", '_DIMS_LABEL_TICKET_DEST_CC'),
        (NULL, 'system', '2', "Carbon copy", '_DIMS_LABEL_TICKET_DEST_CC'),
        (NULL, 'system', '1', "Copie carbone invisible", '_DIMS_LABEL_TICKET_DEST_CCI'),
        (NULL, 'system', '2', "Black carbon copy", '_DIMS_LABEL_TICKET_DEST_CCI');
        