TRUNCATE `dims_action`;
TRUNCATE `dims_action_intercom`;
TRUNCATE `dims_action_matrix`;
TRUNCATE `dims_address`;
TRUNCATE `dims_alerts`;
TRUNCATE `dims_annotation`;
TRUNCATE `dims_annotation_tag`;
TRUNCATE `dims_campaign`;
TRUNCATE `dims_campaign_keyword`;
TRUNCATE `dims_car`;
TRUNCATE `dims_case`;
TRUNCATE `dims_category`;
TRUNCATE `dims_category_module`;
TRUNCATE `dims_category_module_type`;
TRUNCATE `dims_category_object`;
TRUNCATE `dims_chat_msg`;
TRUNCATE `dims_chat_users`;
TRUNCATE `dims_connecteduser`;
TRUNCATE `dims_contact`;
TRUNCATE `dims_contact_languages`;
TRUNCATE `dims_documents_file`;
TRUNCATE `dims_documents_folder`;
TRUNCATE `dims_error`;
TRUNCATE `dims_favorite`;
TRUNCATE `dims_globalobject`;
TRUNCATE `dims_globalobject_link`;
TRUNCATE `dims_globalobject_notation`;
TRUNCATE `dims_history_user_object`;
TRUNCATE `dims_import`;
TRUNCATE `dims_import_champs_fichier_modele`;
TRUNCATE `dims_import_check_fields`;
TRUNCATE `dims_import_correspondance_colonne_champs`;
TRUNCATE `dims_import_fichier_modele`;
TRUNCATE `dims_import_linked`;
TRUNCATE `dims_import_type_champs_fichier_modele`;
TRUNCATE `dims_intercom`;
TRUNCATE `dims_interest`;
TRUNCATE `dims_intervention`;
TRUNCATE `dims_intervention_counter`;
TRUNCATE `dims_intervention_linked`;
TRUNCATE `dims_intervention_link_type`;
TRUNCATE `dims_intervention_type`;
TRUNCATE `dims_jabber_connecteduser`;
TRUNCATE `dims_keywords`;
TRUNCATE `dims_keywords_blacklist`;
TRUNCATE `dims_keywords_campaigncache`;
TRUNCATE `dims_keywords_corresp`;
TRUNCATE `dims_keywords_index`;
TRUNCATE `dims_keywords_metafield`;
TRUNCATE `dims_keywords_metaphone`;
TRUNCATE `dims_keywords_ordercache`;
TRUNCATE `dims_keywords_preindex`;
TRUNCATE `dims_keywords_sentence`;
TRUNCATE `dims_keywords_temp`;
TRUNCATE `dims_keywords_usercache`;
TRUNCATE `dims_languages`;
TRUNCATE `dims_log`;
TRUNCATE `dims_mailinglist`;
TRUNCATE `dims_mailinglist_attach`;
TRUNCATE `dims_mailing_content`;
TRUNCATE `dims_mailing_content_list`;
TRUNCATE `dims_mailing_email`;
TRUNCATE `dims_mailing_list`;
TRUNCATE `dims_matrix`;
TRUNCATE `dims_milestone`;
TRUNCATE `dims_mod_activity_sector`;
TRUNCATE `dims_mod_activity_type`;
TRUNCATE `dims_mod_agenda`;
TRUNCATE `dims_mod_agenda_cat`;
TRUNCATE `dims_mod_agenda_organizer`;
TRUNCATE `dims_mod_article`;
TRUNCATE `dims_mod_article_draft`;
TRUNCATE `dims_mod_article_heading`;
TRUNCATE `dims_mod_business_action`;
TRUNCATE `dims_mod_business_action_detail`;
TRUNCATE `dims_mod_business_action_notification`;
TRUNCATE `dims_mod_business_action_old`;
TRUNCATE `dims_mod_business_action_reponse`;
TRUNCATE `dims_mod_business_action_reponse_value`;
TRUNCATE `dims_mod_business_action_resp`;
TRUNCATE `dims_mod_business_action_utilisateur`;
TRUNCATE `dims_mod_business_activity_contact`;
TRUNCATE `dims_mod_business_commentaire`;
TRUNCATE `dims_mod_business_competence`;
TRUNCATE `dims_mod_business_contact_field`;
TRUNCATE `dims_mod_business_contact_group`;
TRUNCATE `dims_mod_business_contact_group_link`;
TRUNCATE `dims_mod_business_contact_import`;
TRUNCATE `dims_mod_business_contact_import_ent_similar`;
TRUNCATE `dims_mod_business_contact_incomplete`;
TRUNCATE `dims_mod_business_contact_layer`;
TRUNCATE `dims_mod_business_contact_layer_save`;
TRUNCATE `dims_mod_business_contact_mail`;
TRUNCATE `dims_mod_business_contact_mbfield`;
TRUNCATE `dims_mod_business_contact_profil`;
TRUNCATE `dims_mod_business_ct_link`;
TRUNCATE `dims_mod_business_ct_watch`;
TRUNCATE `dims_mod_business_dossier`;
TRUNCATE `dims_mod_business_enum`;
TRUNCATE `dims_mod_business_enum_liens`;
TRUNCATE `dims_mod_business_equipement`;
TRUNCATE `dims_mod_business_event_etap`;
TRUNCATE `dims_mod_business_event_etap_delegue`;
TRUNCATE `dims_mod_business_event_etap_file`;
TRUNCATE `dims_mod_business_event_etap_file_user`;
TRUNCATE `dims_mod_business_event_etap_user`;
TRUNCATE `dims_mod_business_event_inscription`;
TRUNCATE `dims_mod_business_event_model`;
TRUNCATE `dims_mod_business_factures_fournisseurs`;
TRUNCATE `dims_mod_business_interlocuteur`;
TRUNCATE `dims_mod_business_interlocuteur_categorie`;
TRUNCATE `dims_mod_business_list_profil`;
TRUNCATE `dims_mod_business_meta_categ`;
TRUNCATE `dims_mod_business_meta_field`;
TRUNCATE `dims_mod_business_meta_use`;
TRUNCATE `dims_mod_business_netlor_domain`;
TRUNCATE `dims_mod_business_netlor_server`;
TRUNCATE `dims_mod_business_params`;
TRUNCATE `dims_mod_business_print_model`;
TRUNCATE `dims_mod_business_produit`;
TRUNCATE `dims_mod_business_profil`;
TRUNCATE `dims_mod_business_suivi`;
TRUNCATE `dims_mod_business_suivi_detail`;
TRUNCATE `dims_mod_business_suivi_type`;
TRUNCATE `dims_mod_business_tiers`;
TRUNCATE `dims_mod_business_tiers_competence`;
TRUNCATE `dims_mod_business_tiers_contact`;
TRUNCATE `dims_mod_business_tiers_dossier`;
TRUNCATE `dims_mod_business_tiers_equipement`;
TRUNCATE `dims_mod_business_tiers_field`;
TRUNCATE `dims_mod_business_tiers_import`;
TRUNCATE `dims_mod_business_tiers_interlocuteur`;
TRUNCATE `dims_mod_business_tiers_layer`;
TRUNCATE `dims_mod_business_tiers_layer_save`;
TRUNCATE `dims_mod_business_tiers_mbfield`;
TRUNCATE `dims_mod_business_tiers_project`;
TRUNCATE `dims_mod_business_tiers_service`;
TRUNCATE `dims_mod_business_tiers_services`;
TRUNCATE `dims_mod_business_user_planning`;
TRUNCATE `dims_mod_business_versement`;
TRUNCATE `dims_mod_chat_conversation`;
TRUNCATE `dims_mod_chat_message`;
TRUNCATE `dims_mod_chat_message_log`;
TRUNCATE `dims_mod_courrier_folder`;
TRUNCATE `dims_mod_directory_contact`;
TRUNCATE `dims_mod_directory_favorites`;
TRUNCATE `dims_mod_doc_file`;
TRUNCATE `dims_mod_doc_file_draft`;
TRUNCATE `dims_mod_doc_file_history`;
TRUNCATE `dims_mod_doc_folder`;
TRUNCATE `dims_mod_doc_gallery`;
TRUNCATE `dims_mod_elearning_video`;
TRUNCATE `dims_mod_elearning_video_details`;
TRUNCATE `dims_mod_faq_affectation`;
TRUNCATE `dims_mod_faq_question`;
TRUNCATE `dims_mod_faq_reponse`;
TRUNCATE `dims_mod_faq_rubriques`;
TRUNCATE `dims_mod_forms`;
TRUNCATE `dims_mod_forms_field`;
TRUNCATE `dims_mod_forms_reply`;
TRUNCATE `dims_mod_forms_reply_field`;
TRUNCATE `dims_mod_news`;
TRUNCATE `dims_mod_newscat`;
TRUNCATE `dims_mod_newsletter`;
TRUNCATE `dims_mod_newsletter_content`;
TRUNCATE `dims_mod_newsletter_inscription`;
TRUNCATE `dims_mod_newsletter_mailing_ct`;
TRUNCATE `dims_mod_newsletter_mailing_list`;
TRUNCATE `dims_mod_newsletter_mailing_news`;
TRUNCATE `dims_mod_newsletter_subscribed`;
TRUNCATE `dims_mod_newsletter_tag`;
TRUNCATE `dims_mod_opportunity_sector`;
TRUNCATE `dims_mod_opportunity_type`;
TRUNCATE `dims_mod_rsscache`;
TRUNCATE `dims_mod_rsscat`;
TRUNCATE `dims_mod_rssfeed`;
TRUNCATE `dims_mod_rsspref`;
TRUNCATE `dims_mod_rssrequest`;
TRUNCATE `dims_mod_sharefile_contact`;
TRUNCATE `dims_mod_sharefile_file`;
TRUNCATE `dims_mod_sharefile_history`;
TRUNCATE `dims_mod_sharefile_param`;
TRUNCATE `dims_mod_sharefile_share`;
TRUNCATE `dims_mod_sharefile_user`;
TRUNCATE `dims_mod_vcard`;
TRUNCATE `dims_mod_wce_article`;
TRUNCATE `dims_mod_wce_article_ab`;
TRUNCATE `dims_mod_wce_article_block`;
TRUNCATE `dims_mod_wce_article_block_model`;
TRUNCATE `dims_mod_wce_article_block_version`;
TRUNCATE `dims_mod_wce_article_doc`;
TRUNCATE `dims_mod_wce_article_draft`;
TRUNCATE `dims_mod_wce_article_meter`;
TRUNCATE `dims_mod_wce_article_tags`;
TRUNCATE `dims_mod_wce_article_version`;
TRUNCATE `dims_mod_wce_article_visite`;
TRUNCATE `dims_mod_wce_heading`;
TRUNCATE `dims_mod_wce_lang`;
TRUNCATE `dims_mod_wce_object`;
TRUNCATE `dims_mod_wce_object_corresp`;
TRUNCATE `dims_mod_wce_reference`;
TRUNCATE `dims_mod_wce_rule`;
TRUNCATE `dims_mod_wce_rule_corresp`;
TRUNCATE `dims_mod_wce_site`;
TRUNCATE `dims_mod_wce_slideshow`;
TRUNCATE `dims_mod_wce_slideshow_element`;
TRUNCATE `dims_mod_wce_template`;
TRUNCATE `dims_mod_webmail_email`;
TRUNCATE `dims_mod_webmail_email_adresse`;
TRUNCATE `dims_mod_webmail_email_docfile`;
TRUNCATE `dims_mod_webmail_email_link`;
TRUNCATE `dims_mod_webmail_inbox`;
TRUNCATE `dims_mod_ww_email`;
TRUNCATE `dims_mod_ww_inbox`;
TRUNCATE `dims_mod_ww_page`;
TRUNCATE `dims_mod_ww_site`;
TRUNCATE `dims_param_block_user`;
TRUNCATE `dims_profile`;
TRUNCATE `dims_project`;
TRUNCATE `dims_project_milestone`;
TRUNCATE `dims_project_user`;
TRUNCATE `dims_search_expression`;
TRUNCATE `dims_search_expression_result`;
TRUNCATE `dims_search_expression_tag`;
TRUNCATE `dims_selection_categ`;
TRUNCATE `dims_share`;
TRUNCATE `dims_tag`;
TRUNCATE `dims_tag_globalobject`;
TRUNCATE `dims_tag_index`;
TRUNCATE `dims_task`;
TRUNCATE `dims_task_user`;
TRUNCATE `dims_ticket`;
TRUNCATE `dims_ticket_dest`;
TRUNCATE `dims_ticket_object`;
TRUNCATE `dims_ticket_status`;
TRUNCATE `dims_ticket_watch`;
TRUNCATE `dims_todo`;
TRUNCATE `dims_todo_dest`;
TRUNCATE `dims_user_abonnt`;
TRUNCATE `dims_user_action_log`;
TRUNCATE `dims_user_address`;
TRUNCATE `dims_user_ask_password`;
TRUNCATE `dims_user_car`;
TRUNCATE `dims_user_facture`;
TRUNCATE `dims_user_filter_rules`;
TRUNCATE `dims_user_history_object`;
TRUNCATE `dims_user_interest`;
TRUNCATE `dims_user_type`;
TRUNCATE `dims_user_type_fields`;
TRUNCATE `dims_user_works`;
TRUNCATE `dims_workflow`;
TRUNCATE `dims_works`;

DELETE FROM `dims_user` WHERE id != 63;
DELETE FROM `dims_group` WHERE id > 3;
DELETE FROM `dims_group_user` WHERE id_user NOT IN ( SELECT id FROM `dims_user` );
DELETE FROM `dims_group_user` WHERE id_group NOT IN ( SELECT id FROM `dims_group` );
DELETE FROM `dims_mod_business_contact` WHERE id NOT IN ( SELECT id_contact FROM `dims_user` );

UPDATE `dims_user` SET lastname = 'admin', firstname = 'admin', login = 'admin', password = MD5('admin'), email = 'admin@example.com', date_creation = '20121116100000', lastconnexion = NULL, beforelastconnexion = NULL, id_skin = 24 WHERE id = 63;
UPDATE `dims_mod_business_contact` c, `dims_user` u SET
	c.lastname = u.lastname,
	c.firstname = u.firstname,
	c.photo = NULL,
	c.email = u.email,
	c.date_create = '20121116100000',
	c.timestp_modify = '20121116100000',
	c.id_globalobject = 0
WHERE c.id = u.id_contact;

DELETE FROM `dims_workspace_user` WHERE id_user NOT IN ( SELECT id FROM `dims_user` );
DELETE FROM `dims_workspace` WHERE depth > 2 AND id NOT IN ( SELECT id_workspace FROM `dims_workspace_user` );
DELETE FROM `dims_workspace_user_role` WHERE id_user NOT IN ( SELECT id FROM `dims_user` );
DELETE FROM `dims_workspace_user_role` WHERE id_workspace NOT IN ( SELECT id FROM `dims_workspace` );
DELETE FROM `dims_workspace_template` WHERE id_workspace NOT IN ( SELECT id FROM `dims_workspace` );
DELETE FROM `dims_workspace_share` WHERE id_from NOT IN ( SELECT id FROM `dims_workspace` ) OR id_to NOT IN ( SELECT id FROM `dims_workspace` );
DELETE FROM `dims_workspace_group` WHERE id_workspace NOT IN ( SELECT id FROM `dims_workspace` );
DELETE FROM `dims_workspace_group` WHERE id_group NOT IN ( SELECT id FROM `dims_group` );
DELETE FROM `dims_workspace_group_role` WHERE id_workspace NOT IN ( SELECT id FROM `dims_workspace` );
DELETE FROM `dims_workspace_group_role` WHERE id_group NOT IN ( SELECT id FROM `dims_group` );
DELETE FROM `dims_workspace_domain` WHERE id_workspace NOT IN ( SELECT id FROM `dims_workspace` );
DELETE FROM `dims_domain` WHERE id NOT IN ( SELECT id_domain FROM `dims_workspace_domain` );

DELETE FROM `dims_module_workspace` WHERE id_workspace > 0 AND id_workspace NOT IN ( SELECT id FROM `dims_workspace` );
DELETE FROM `dims_module` WHERE id NOT IN ( SELECT id_module FROM `dims_module_workspace` );
UPDATE `dims_workspace` SET `ssl` = 0 ;
